ALTER FUNCTION [dbo].[Split]
(
	@TEXT VARCHAR(MAX)=''
	,@DELIMETER VARCHAR(1)=','
)
RETURNS @TABLE TABLE 
(
	CODE VARCHAR(500) NOT NULL
)
AS
BEGIN
	DECLARE @XML AS XML

	SET @XML = CAST(('<X>'+REPLACE(@TEXT,@DELIMETER ,'</X><X>')+'</X>') AS XML)

	DECLARE @temp TABLE (ID INT)

	INSERT INTO @TABLE

	SELECT N.value('.', 'VARCHAR(500)') FROM @XML.nodes('X') AS T(N)
	RETURN;
END